# Site Settings
# title: BSc MSc MRes EngD CGeog (GIS) FRGS
title: KELVIN WONG
# description: > # Text below
#   A 3D geospatial scientist, chartered geographer, and fellow of The Royal Geographical Society with over nine years of experience of business-oriented research. I enjoy working on the boundary of research and business, where I can innovate while addressing real-world and tangible challenges. Interdisciplinary in nature, I have worked in many different domains from transport planning to human behaviour understanding to autonomous vehicles. 
#   <br><br>
#   My overall approach focuses on two key principles: user-centric design, and data quality. I want to deliver high quality analysis that decision makers and stakeholders can trust, providing them with useful business insight for data-informed decisions by leveraging the power of geospatial data.
#   <br><br>
#   <a href="https://www.linkedin.com/in/wongkelvin">View My LinkedIn Profile</a>
#   <br><br>
#   <a href="https://1drv.ms/b/s!AuQRk-S_lsLklLMRah3udAf_1W2CxQ?e=2Tb6ZS" target="_blank">Download CV Here (PDF)</a>
logo: /icon.png
email: kelvinwong@outlook.com
github: is\_project\_page:false
minima:
  skin: shinkansen
  social_links:
    twitter: kel_196
#     github: kel196
#     stackoverflow: "11111"
#     dribbble: jekyll
#     facebook: jekyll
#     flickr: jekyll
#     instagram: jekyll
    linkedin: wongkelvin
#     pinterest: jekyll
#     telegram: jekyll
#     microdotblog: jekyll
#     keybase: jekyll

# Google Analytics
google_analytics: UA-48477520-1

# Build Settings
theme: jekyll-theme-minimal

